### ISSUE TITLE
无法更新战绩

### ISSUE THREAD

**Issue by comradeXiong** [ZegWe/Dota2Bot#3]
大佬你好，感谢你开源了这个BOT。我发现了程序有两个问题。
1. 
![image](https://user-images.githubusercontent.com/71760019/102784512-7bdc5900-43d7-11eb-8852-5914d09e6510.png)
频繁建立连接，断开连接。
2.
![image](https://user-images.githubusercontent.com/71760019/102785095-5e5bbf00-43d8-11eb-9c54-29f52fbbcf70.png)
在监视别人以后，无法更新战绩，我在watcher.py 文件中的_update函数中的while循环里面添加了print("test")，结果发现命令行中并没有在间隔时间后打印测试语句，可能是这附近有问题。希望大佬能改一下。Orz

**Comment by ZegWe** [comment]
1. 一直断开连接可能是Python socketio的问题，因为有自动重连所以不太影响使用
2. 我这边是正常的，能贴一下修改后的代码片段吗

**Comment by comradeXiong** [comment]
![image](https://user-images.githubusercontent.com/71760019/102857551-9bb95e80-4463-11eb-9d35-fe0389adf12a.png)

**Comment by ZegWe** [comment]
> ![image](https://user-images.githubusercontent.com/71760019/102857551-9bb95e80-4463-11eb-9d35-fe0389adf12a.png)
> 

暂时看不出什么问题，log里test输出了三次，循环应该是有在进行的。我怀疑可能是战绩查询的时候有问题，你可以试着输出match id看有没有比赛编号

**Comment by comradeXiong** [comment]
现在突然可以正常使用了，很玄学，就是有个问题，战绩时间快了8个小时，应该是 time.localtime(match['start_time'] + 8*60*60这个地方的原因，要是在你那边正常应该是python库函数的问题了

**Comment by ZegWe** [comment]
> 现在突然可以正常使用了，很玄学，就是有个问题，战绩时间快了8个小时，应该是 time.localtime(match['start_time'] + 8*60*60这个地方的原因，要是在你那边正常应该是python库函数的问题了

这个你删掉就好了，我自己放服务器上懒得判时区就直接加了

**Comment by ZegWe** [comment]
> 大佬你好，感谢你开源了这个BOT。我发现了程序有两个问题。
> 1.
> ![image](https://user-images.githubusercontent.com/71760019/102784512-7bdc5900-43d7-11eb-8852-5914d09e6510.png)
> 频繁建立连接，断开连接。
> 2.
> ![image](https://user-images.githubusercontent.com/71760019/102785095-5e5bbf00-43d8-11eb-9c54-29f52fbbcf70.png)
> 在监视别人以后，无法更新战绩，我在watcher.py 文件中的_update函数中的while循环里面添加了print("test")，结果发现命令行中并没有在间隔时间后打印测试语句，可能是这附近有问题。希望大佬能改一下。Orz

频繁重连的问题现在已经解决了， 是socketio版本的问题，可以查看这个issue
https://github.com/xiyaowong/botoy/issues/14#issuecomment-761587743

另外时区问题现在使用pytz这个库来判断，不需要手动计算时间差了（
