### ISSUE TITLE
哈喽，我尝试了很久还没实现

### ISSUE THREAD

**Issue by PuckBlink** [ZegWe/Dota2Bot#4]
py脚本成功运行了，opqbot也在运行了，但对指令没有做出回复的样子，这是什么情况？

2021-10-31 19:19:52.928 | INFO | {'DOTA2每日运势': <class 'plugins.dota2fortune.Fortune'>, 'DOTA2战绩播报': <class 'plugins.dota2watcher.watcher.Watcher'>, 'DOTA2战绩图': <class 'plugins.dota2mdi.Mdi'>}
2021-10-31 19:19:52.930 | SUCCESS | Plugin Manager(9918xxxx) Initialized.

忘了说了，config.json里面的'mdi_url'是什么，我看到你给的范例里面没有，但后面读json时候又调用的，不删就会报错

**Comment by ZegWe** [comment]
mdi是前段时间写的一个新插件，暂时还没有写进文档里，你可以添加一个空的字符串或者在config.py里将那一条删掉

**Comment by PuckBlink** [comment]
那现在的代码能正常实现吗，我真的鼓捣了一天没成功。python的日志你可以看到如上，opq的日志就是在间隔心跳，然后有收到qq群消息，但是没有反应。我觉得是脚本和机器人间没有连通，我这样在json里面正确填写opq_url，浏览器打开这个url/+v1/LuaApiCaller，却只能看到一个，[] offline的返回。

**Comment by ZegWe** [comment]
连接上opq之后应该会有一个connection established的输出，这个有吗

**Comment by PuckBlink** [comment]
> 连接上opq之后应该会有一个connection established的输出，这个有吗

没有，python的日志止步于SUCCESS | Plugin Manager(991842780) Initialized.

**Comment by PuckBlink** [comment]
> 连接上opq之后应该会有一个connection established的输出，这个有吗

我其实不太确定我的opq_url是对的，127.0.0.1是对的吗，还是说我的本地ip

**Comment by ZegWe** [comment]
那就是没有连上，opqurl是不带任何路径的，你看看有没有问题

**Comment by ZegWe** [comment]
需要加上端口号

**Comment by PuckBlink** [comment]
加上端口号了，我的本地ip，"opq_url": "http://192.168.128.12:2333",
![image](https://user-images.githubusercontent.com/46714224/139582416-fc7f4acf-a94e-4a7c-896a-87d1caa7075b.png)

**Comment by ZegWe** [comment]
你在浏览器里访问这个地址能进入opq的管理面板吗

**Comment by PuckBlink** [comment]
> 你在浏览器里访问这个地址能进入opq的管理面板吗

不能，不过这应该是没装那个panel的原因吧，我不知道

**Comment by PuckBlink** [comment]
我打开http://192.168.128.12:2333/v1/LuaApiCaller，返回是[] offline，http://192.168.128.12:2333/返回是.DS_Store

**Comment by PuckBlink** [comment]
所以是panel的原因吗，panel是依赖项吗

**Comment by ZegWe** [comment]
应该不是，使用的socketio和opq交互，你试试把配置里的debug打开看看有没有其他的log

**Comment by PuckBlink** [comment]
2021-10-31 20:37:41.950 | DEBUG | __main__:<module>:55 - Connecting to server...
2021-10-31 20:37:42.952 | DEBUG | plugins.dota2watcher.watcher:update:67 - Watch Loop started: 991842780
卡在这一步

**Comment by PuckBlink** [comment]
老哥要不加群细说，我群号都留了

**Comment by ZegWe** [comment]
还是没连上的问题，我这边是一直都可以的。

**Comment by PuckBlink** [comment]
会不会是我的opq的版本的问题，新版本不支持一类通信方式了？

**Comment by PuckBlink** [comment]
你的opq是哪个版本？

**Comment by PuckBlink** [comment]
还有我的socketio是4.6版本的

**Comment by ZegWe** [comment]
不知道是不是opq新版新版更新socket io版本了，老版必须在低版本才能连上，你试试更新一下依赖里的socketio版本，或者写一个test.py连一下试试，打开socket io的logger

**Comment by PuckBlink** [comment]
我先更新socketio版本吧，我刚才试了下pooling显示 Unexpected status code 503 in server response

**Comment by PuckBlink** [comment]
好吧，是包里面的新参数


不一样了，
  File "C:\Anaconda3\envs\Dota2Bot-new\lib\site-packages\socketio\client.py", line 308, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect

我把socketio更新到5.1.0，包里面报错了

![image](https://user-images.githubusercontent.com/46714224/139586159-6c4c2602-20fa-4171-a180-e02f28b71ec5.png)

**Comment by PuckBlink** [comment]
Connection established.
解决了，装了5.1.0的包，wait=False就行了，谢了

**Comment by PuckBlink** [comment]
唉， [steam_id]是64位id吗，个人资料url上的17位数字？我!添加监视报错呀

**Comment by ZegWe** [comment]
九位或者十位吧，游戏里那个好友id

**Comment by PuckBlink** [comment]
太感谢您了，能跑起来真的太不容易了，读您的说明文档没读清楚。我算是初阶的python学习者吧，今天仔细看了下代码，才搞懂一些问题，比如命令是不能带中括号的。另外有些python开发的事情想问问您，我注意到你对这些功能的实现写了很规范很复杂的类，这种习惯这种层次是如何达到的，（虽然我不了解socketio），我感觉我完全想不到这样写代码来处理信息。

**Comment by ZegWe** [comment]
其实我自己也写得挺烂的，主要就是参考一些已有的开源代码，然后自己改改吧，多写就好了

**Comment by PuckBlink** [comment]
但是今天我遇到了另一个问题，就是连接过几分钟后，就一直在断线并重连，然后很快又能连上。虽然指令都能反馈，但是战报功能却还没成功过，日志里面的“updating...”在刚连接后还有，但是一直在断线并重连期间，就没有“updating...”的日志了。老哥你清楚这是什么情况吗？
2021-11-01 17:09:21.426 | WARNING | __main__:disconnect:40 - Disconnected from server
2021-11-01 17:09:22.460 | SUCCESS | __main__:connect:16 - Connection established.

**Comment by ZegWe** [comment]
‘updating...’是每一轮更新开始时输出的，目前内置五分钟进行一次
一直断线重连可能是网络不稳定，也可能是socketio版本问题，我试了一下我这边是不会有问题的，版本按照requirements里写的，没有任何改动
